version: 2.1

# ====================
# WORKFLOW DECLARATION
# ====================
workflows:
  version: 2
  main:
    jobs:
      - vint
      - semantic_release:
          requires:
            - vint
          filters:
            branches:
              only:
                - master

# ====================
# ALIASES
# ====================
base_image: &base_image
  docker:
    - image: python:3.6-alpine
  working_directory: /home/circleci/project/

install_dependencies: &install_dependencies
  run:
    name: Install dependencies.
    command: |
      pip install -U pip && pip install vim-vint

lint: &lint
  run:
    name: Run vint.
    command: vint .

restore_cache: &restore_cache
  restore_cache:
    keys:
      - dependencies-{{ checksum "yarn.lock" }}
      - dependencies-

save_cache: &save_cache
  save_cache:
    paths:
      - node_modules/
    key: dependencies-{{ checksum "yarn.lock" }}

install_node_dependencies: &install_node_dependencies
  run:
    name: Install dependencies from `package.json`.
    command: yarn -s --frozen-lockfile

# ================
# JOB DECLARATIONS
# ================
jobs:
  vint:
    <<: *base_image
    steps:
      - checkout
      - *install_dependencies
      - *lint

  semantic_release:
    docker:
      - image: node:12-alpine
    working_directory: /home/circleci/project/
    steps:
      - checkout
      - *restore_cache
      - *install_node_dependencies
      - *save_cache
      - run: yarn semantic_release
